version: "3.8"
services:
  api:
    build: .
    ports:
      - "8787:8787"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # In production, we don't need volumes as files are copied during build
