app = "congress-legislators-api"  # replace with your app name

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8787"

[http_service]
  internal_port = 8787
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8787
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"] 